-- Add sample posts to test the Content Library (FIXED VERSION)
-- Run this AFTER running update-posts-table.sql

-- Clear any existing sample posts first (optional)
-- DELETE FROM posts WHERE user_id = auth.uid() AND content LIKE '%test%';

-- Add sample posts for the current user
INSERT INTO posts (user_id, content, platforms, status, published_at, generated_by_ai, engagement_stats) VALUES
(auth.uid(), '🎉 Welcome to your Content Library! This is your first post to test the system. Everything is working perfectly!', ARRAY['twitter'], 'published', NOW() - INTERVAL '2 hours', false, '{"twitter": {"likes": 15, "shares": 3, "comments": 2}}'),

(auth.uid(), '🚀 Testing multi-platform posting with LinkedIn and Twitter integration. The future of social media management is here!', ARRAY['linkedin', 'twitter'], 'published', NOW() - INTERVAL '1 day', false, '{"linkedin": {"likes": 25, "shares": 8}, "twitter": {"likes": 12, "shares": 4}}'),

(auth.uid(), '📝 Draft post for Instagram - still working on this content... Need to add some emojis and hashtags to make it perfect!', ARRAY['instagram'], 'draft', null, false, '{}'),

(auth.uid(), '⏰ Scheduled post for tomorrow morning announcement. Big news coming soon! Stay tuned for exciting updates.', ARRAY['twitter', 'linkedin'], 'scheduled', NOW() + INTERVAL '1 day', false, '{}'),

(auth.uid(), '🤖 This post was generated by AI to demonstrate the AI content tracking feature. Pretty cool, right?', ARRAY['twitter'], 'published', NOW() - INTERVAL '3 hours', true, '{"twitter": {"likes": 8, "shares": 2}}'),

(auth.uid(), '❌ This is an example of a failed post to show error handling in the Content Library interface.', ARRAY['facebook'], 'failed', null, false, '{}');

-- Update the failed post with an error message
UPDATE posts 
SET error_message = 'Facebook API authentication failed. Please reconnect your Facebook account.'
WHERE user_id = auth.uid() AND status = 'failed' AND platforms @> ARRAY['facebook'];

-- Add a post with an image
INSERT INTO posts (user_id, content, platforms, status, published_at, image_url, generated_by_ai) VALUES
(auth.uid(), '📸 Check out this amazing image post! Visual content performs so much better on social media.', ARRAY['instagram', 'twitter'], 'published', NOW() - INTERVAL '6 hours', 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=500', false);

-- Add a Reddit post
INSERT INTO posts (user_id, content, platforms, status, published_at, generated_by_ai) VALUES
(auth.uid(), '🔥 Just discovered this amazing social media scheduler! Perfect for managing multiple platforms. What tools do you use?', ARRAY['reddit'], 'published', NOW() - INTERVAL '4 hours', false);

-- Add a multi-platform scheduled post
INSERT INTO posts (user_id, content, platforms, status, scheduled_for, generated_by_ai) VALUES
(auth.uid(), '🌟 Exciting announcement coming this weekend! Our biggest update yet is almost ready. #ComingSoon #SocialMedia', ARRAY['twitter', 'linkedin', 'facebook'], 'scheduled', NOW() + INTERVAL '2 days', false);

-- Verify the data was inserted
SELECT 
  id,
  LEFT(content, 50) as content_preview,
  platforms,
  status,
  created_at,
  generated_by_ai,
  error_message
FROM posts 
WHERE user_id = auth.uid() 
ORDER BY created_at DESC;
