-- Add sample posts with explicit user ID
-- REPLACE 'YOUR_USER_ID_HERE' with your actual user ID from find-user-id.sql

-- Step 1: Find your user ID first by running find-user-id.sql
-- Step 2: Replace 'YOUR_USER_ID_HERE' below with your actual user ID
-- Step 3: Run this script

-- Replace this with your actual user ID:
-- Example: SET @user_id = '12345678-1234-1234-1234-123456789012';

-- Add sample posts for testing
INSERT INTO posts (user_id, content, platforms, status, published_at, generated_by_ai, engagement_stats) VALUES
('YOUR_USER_ID_HERE', '🎉 Welcome to your Content Library! This is your first post to test the system. Everything is working perfectly!', ARRAY['twitter'], 'published', NOW() - INTERVAL '2 hours', false, '{"twitter": {"likes": 15, "shares": 3, "comments": 2}}'),

('YOUR_USER_ID_HERE', '🚀 Testing multi-platform posting with LinkedIn and Twitter integration. The future of social media management is here!', ARRAY['linkedin', 'twitter'], 'published', NOW() - INTERVAL '1 day', false, '{"linkedin": {"likes": 25, "shares": 8}, "twitter": {"likes": 12, "shares": 4}}'),

('YOUR_USER_ID_HERE', '📝 Draft post for Instagram - still working on this content... Need to add some emojis and hashtags to make it perfect!', ARRAY['instagram'], 'draft', null, false, '{}'),

('YOUR_USER_ID_HERE', '⏰ Scheduled post for tomorrow morning announcement. Big news coming soon! Stay tuned for exciting updates.', ARRAY['twitter', 'linkedin'], 'scheduled', NOW() + INTERVAL '1 day', false, '{}'),

('YOUR_USER_ID_HERE', '🤖 This post was generated by AI to demonstrate the AI content tracking feature. Pretty cool, right?', ARRAY['twitter'], 'published', NOW() - INTERVAL '3 hours', true, '{"twitter": {"likes": 8, "shares": 2}}'),

('YOUR_USER_ID_HERE', '❌ This is an example of a failed post to show error handling in the Content Library interface.', ARRAY['facebook'], 'failed', null, false, '{}');

-- Update the failed post with an error message
UPDATE posts 
SET error_message = 'Facebook API authentication failed. Please reconnect your Facebook account.'
WHERE user_id = 'YOUR_USER_ID_HERE' AND status = 'failed' AND platforms @> ARRAY['facebook'];

-- Add a post with an image
INSERT INTO posts (user_id, content, platforms, status, published_at, image_url, generated_by_ai) VALUES
('YOUR_USER_ID_HERE', '📸 Check out this amazing image post! Visual content performs so much better on social media.', ARRAY['instagram', 'twitter'], 'published', NOW() - INTERVAL '6 hours', 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=500', false);

-- Add a Reddit post
INSERT INTO posts (user_id, content, platforms, status, published_at, generated_by_ai) VALUES
('YOUR_USER_ID_HERE', '🔥 Just discovered this amazing social media scheduler! Perfect for managing multiple platforms. What tools do you use?', ARRAY['reddit'], 'published', NOW() - INTERVAL '4 hours', false);

-- Add a multi-platform scheduled post
INSERT INTO posts (user_id, content, platforms, status, scheduled_for, generated_by_ai) VALUES
('YOUR_USER_ID_HERE', '🌟 Exciting announcement coming this weekend! Our biggest update yet is almost ready. #ComingSoon #SocialMedia', ARRAY['twitter', 'linkedin', 'facebook'], 'scheduled', NOW() + INTERVAL '2 days', false);

-- Verify the data was inserted
SELECT 
  id,
  LEFT(content, 50) as content_preview,
  platforms,
  status,
  created_at,
  generated_by_ai,
  error_message
FROM posts 
WHERE user_id = 'YOUR_USER_ID_HERE' 
ORDER BY created_at DESC;
